### ISSUE TITLE
Surround top level declarations in Solidity source with two blank lines.

### ISSUE THREAD

**Issue by CaixiangFan** [0xzhiqi/W2-Project#1]
Hi Solidity style guide suggests two blank lines for top level declarations.
https://github.com/0xzhiqi/W2-Project/blob/6250a7f3b68962af854c01978b98c67e0bcd9e28/contracts/CustomBallot.sol#L8

**Comment by 0xzhiqi** [comment]
Oh yes, let me add the missing blank line
