### ISSUE TITLE
External function should go before public

### ISSUE THREAD

**Issue by CaixiangFan** [0xzhiqi/W2-Project#2]
Hi Solidity style guide suggests external functions placed before public functions. So, it could be better to put winnerName() before winningProposal().
https://github.com/0xzhiqi/W2-Project/blob/6250a7f3b68962af854c01978b98c67e0bcd9e28/contracts/CustomBallot.sol#L8

**Comment by 0xzhiqi** [comment]
Oh yes, my order is not right. Let me change it
