### ISSUE TITLE
Not necessarily slicing the args

### ISSUE THREAD

**Issue by CaixiangFan** [0xzhiqi/W2-Project#4]
Hi, you can directly access the argument by its index (process.argv[3]) rather than slicing and then accessing via index. It will take the last argument rather than the 4th one if users give more than 2 args by mistake.
https://github.com/0xzhiqi/W2-Project/blob/6250a7f3b68962af854c01978b98c67e0bcd9e28/scripts/mintTokens.ts#L41

**Comment by 0xzhiqi** [comment]
I see. I was actually quite unsure what's the right way to go about this as I am not familiar with accessing arguments from ts-node. Thanks for showing me the better way to do it!
