### ISSUE TITLE
Provider code can be reused

### ISSUE THREAD

**Issue by CaixiangFan** [0xzhiqi/W2-Project#5]
Hi, the code for connecting service provider can be wrapped into a single .ts file and reused anywhere necessary for easier maintenance and readability. 
https://github.com/0xzhiqi/W2-Project/blob/6250a7f3b68962af854c01978b98c67e0bcd9e28/scripts/getVotingPowerForSelf.ts#L24

**Comment by 0xzhiqi** [comment]
Yes agree. Will create a new file for this
